### PR TITLE
Release Version `1.1.0`: Adds `build-metadata` output and adds support for manually triggered workflows

### PR DESCRIPTION
**Pull request by QuintinWillison**
I would like to start using this action in [the Asset Tracking Android repository](https://github.com/ably/ably-asset-tracking-android), in order to append this additional, conformed build context to version numbers of example app builds released to Firebase App Distribution. This will be achieved using a _new_ workflow, based on [the _existing_ `publish-example-apps`](https://github.com/ably/ably-asset-tracking-android/blob/main/.github/workflows/publish-example-apps.yml), but which will allow adhoc builds to be published without needing to push a 'formal' Git tag. It is expected these will include:

- Builds from `HEAD` of the default (`main`) branch
- Builds from `HEAD` of the branch underlying a given pull request

The net result will be increased team velocity when needing to "cut a release" for manual QA testing, without the need to go through a "whole SDK" formal release process.

This action has been in use for some time already in [the `assemble` workflow within the spec repository](https://github.com/ably/specification/blob/main/.github/workflows/assemble.yml).

### CODE REVIEW

**Review by Peter-Maguire — APPROVED** [review]

**Review by owenpearson — APPROVED** [review]
LGTM 👍

**Review by mohyour — APPROVED** [review]

**Comment by QuintinWillison** [comment]
Unfortunately this doesn't do what I need it to do at the upstream call site. It's being used [from a manually triggered workflow](https://github.com/ably/ably-asset-tracking-android/blob/4a6678b52455ef4ace6761db6c1f915f19ce18a1/.github/workflows/adhoc-publish-example-apps.yml#L6), which is a path [not yet supported by this action](https://github.com/ably/ably-asset-tracking-android/actions/runs/4055492251/jobs/6978704554#step:3:3) (`Error: this action can only be ran on a pull_request, a push to the 'main' branch, or a push of a tag`). Putting this PR back to Draft state while I think and then work on it. I would expect the changes that I'll need to make to be big enough to require me to re-request reviews.

**Comment by QuintinWillison** [comment]
[This AAT workflow run](https://github.com/ably/ably-asset-tracking-android/actions/runs/4063888991/jobs/6996657409#step:3:1) shows this in action as at https://github.com/ably/github-event-context-action/pull/2/commits/3566930281aedb2604d45fe2e933383c59073d8e, currently [pinned to the branch underlying this PR](https://github.com/ably/ably-asset-tracking-android/blob/4a6678b52455ef4ace6761db6c1f915f19ce18a1/.github/workflows/adhoc-publish-example-apps.yml#L28):

```
##[group***Run ably/github-event-context-action@add-build-metadata-output-and-release
##[endgroup***
GITHUB_ACTOR: "QuintinWillison"
GITHUB_BASE_REF: ""
GITHUB_EVENT_NAME: "workflow_dispatch"
GITHUB_EVENT_PATH: "/home/runner/work/_temp/_github_workflow/event.json"
GITHUB_HEAD_REF: ""
GITHUB_REF: "refs/heads/main"
GITHUB_REF_NAME: "main"
GITHUB_REF_TYPE: "branch"
GITHUB_RUN_ATTEMPT: "1"
GITHUB_RUN_ID: "4063888991"
GITHUB_RUN_NUMBER: "7"
GITHUB_SHA: "4a6678b52455ef4ace6761db6c1f915f19ce18a1"
GITHUB_WORKFLOW: "Adhoc Publish Example Apps"
context.eventName: "workflow_dispatch"
context.sha: "4a6678b52455ef4ace6761db6c1f915f19ce18a1"
ref.type: "head"
ref.name: "main"
sha: 4a6678b52455ef4ace6761db6c1f915f19ce18a1
url: https://github.com/ably/ably-asset-tracking-android/actions/runs/4063888991/attempts/1
title: Manually Triggered: Adhoc Publish Example Apps
build-metadata: main-4a6678b
```

**Review by owenpearson — APPROVED** [review]
Looks great!

**Pull request merged**
